### ISSUE TITLE
Обсуждение Rust macros facility proposal

### ISSUE THREAD

**Issue by alexander-irbis** [AdHoc-Protocol/AdHoc-protocol#3]
https://github.com/cheblin/BlackBox/wiki/Rust-macros-facility-proposal

**Comment by alexander-irbis** [comment]
Есть ли языки, где подобное реализовано, как пример?

Как эта функциональность должна вести себя при переходе через границу крейта?

У меня есть опасение, что концепция для небольших вещей выглядит красиво, но когда сущностей становится много - можно легко запутаться и придётся заодно разгребать ошибки сортировки.

Как workaround: когда мне нужно было отсортировать раскрытие макросов, я делал это расположив модули в нужном (не алфавитном) порядке.

**Comment by cheblin** [comment]
> Есть ли языки, где подобное реализовано, как пример?

не знаю. это просто моя хотелка. 
В целом у меня сложилось впечатление, что всё развитие системы макросов в Rust отталкивалось от потребностей таких флагманских проектов как `serde`, `disel`  и тд.

>при переходе через границу крейта

у каждого крэйта при компиляции, строится свой независимый AST.  из этого и исходим.  
я смотрел исходники компилятора и даже примерно представляю место, где нужно добавить код для получения желаемой функциональности. 
 
> разгребать ошибки сортировки.

а нет никаких ошибок. если индексы различны - все произойдет согласно сортировки по индексу 
у макросов с одинаковыми значениями порядка сортировки, порядок внутри группы не определён.

к примеру если обнаружены индексы

**0, 1, 1, 1, 1, 56, 457.**

то макросы с индексом 1 будут гарантированно развернуты позже макроса с индексом 0, но раньше чем с индексом 56. 

порядок же раскрытия макросов внутри группы с индексами 1 не предопределён.  хочется определённости  - делай разные индексы 

если кто то боится запутаться в очередности раскрытия макросов, пусть всем макросам которые должны раскрываться в последнюю очередь присвоит одинаковые  индексы. например **887**

тем самым макросы разделятся на две части - те, которые раскрываются как обычно и те, которые **гарантированно  раскрываются после обычных**.
